# Generated by Django 3.1.3 on 2021-01-02 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=60)),
                ('address_line_2', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('guid', models.CharField(max_length=36)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentVersions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=50)),
                ('version', models.SmallIntegerField(verbose_name=6)),
                ('uploaded_time', models.DateTimeField()),
                ('extension', models.CharField(max_length=9)),
                ('content_type', models.CharField(max_length=75)),
                ('size', models.IntegerField()),
                ('documents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.documents')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], max_length=1)),
                ('email_address', models.EmailField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('deleted', models.BooleanField()),
                ('addressdetails', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addressdetails', to='emp.addressdetails')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='emp.roles')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.documentversions')),
                ('employees', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.employees')),
            ],
        ),
        migrations.AddField(
            model_name='documentversions',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.employees'),
        ),
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('documentversions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.documentversions')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='emp.documentfolder')),
            ],
        ),
    ]
