# Generated by Django 3.1.3 on 2021-01-02 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='addressdetails',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addressdetails', to='emp.addressdetails'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employees',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='emp.roles'),
        ),
    ]
