# Generated by Django 3.1.3 on 2021-01-04 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0003_auto_20210102_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='roles',
        ),
    ]
